CREATE TABLE IF NOT EXISTS events (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 ts INTEGER NOT NULL,
 ip TEXT NOT NULL,
 method TEXT NOT NULL,
 path TEXT NOT NULL,
 country TEXT,
 ua TEXT,
 risk INTEGER NOT NULL,
 action TEXT NOT NULL,
 threat TEXT,
 reason TEXT,
 ai TEXT,
 latency_ms INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts DESC);
CREATE INDEX IF NOT EXISTS idx_events_ip ON events(ip);
CREATE INDEX IF NOT EXISTS idx_events_action ON events(action);

CREATE TABLE IF NOT EXISTS bans (
 ip TEXT PRIMARY KEY,
 created_at INTEGER NOT NULL,
 expires_at INTEGER NOT NULL,
 reason TEXT,
 score INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS allowlist (ip TEXT PRIMARY KEY, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS policies (
 key TEXT PRIMARY KEY,
 value TEXT NOT NULL,
 updated_at INTEGER NOT NULL
);
